# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    tags: [ '*.*.*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build solution
      run: dotnet build -c release      
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Pack UnGet package  
      run: dotnet pack -c release -o ./output -p:PackageVersion=${{ github.ref_name }}

    - name: Publish to NuGet.org
      run: dotnet nuget push ./output/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
